### ISSUE TITLE
`outline-minor-mode` and `jit-spell-correct-word`

### ISSUE THREAD

**Issue by aikrahguzar** [astoff/jit-spell#15]
I use `outline-minor-mode` quite a lot and keep body of most of the headings invisible. As a result when I call `jit-spell-correct-word` it sometimes finds a misspelling in a hidden body and then the interface becomes quite confusing.

I think it makes sense to do what `isearch` does and open invisible overlays. I can implement this if you agree with this feature. Apart from implementing some bespoke mechanism I think the options are:

1. Use isearch mechanism. This is nice because it should allow us to work with a standard protocol. However annoyingly, the implementation of the protocol by `outline-minor-mode` is not complaint and relies on where `isearch` leaves the  point. But that is easy enough to work around.

2. Special case `outline-minor-mode` and handle its overlays only.

I am more inclined towards the first options. Please let me know what you think.

**Comment by astoff** [comment]
Hi, thanks for writing. I'm wondering if it wouldn't make more sense to _skip_ the hidden text instead of unhiding it. In other words, correct the nearest misspelled word that is actually visible.

For one thing, by the nature of jit-lock, we can't even be sure that the hidden text are was spellchecked, It may be partially checked; anything really can happen.

**Comment by aikrahguzar** [comment]
> Hi, thanks for writing. I'm wondering if it wouldn't make more sense to _skip_ the hidden text instead of unhiding it. In other words, correct the nearest misspelled word that is actually visible.
> 
> For one thing, by the nature of jit-lock, we can't even be sure that the hidden text are was spellchecked, It may be partially checked; anything really can happen.

Skipping is a better option is some respects. Actually one of my annoyances was that invalid matches in the invisible text were reported, but I couldn't even see where they were coming from. So I think some part of `jit-lock` fontification skips invisible text but jit-lock calls the `jit-lock-functions` on invisible text. Does the `fontified` property gets set on the invisible text in this location?

If it is not, I think the best thing would be to rely on `fontified` property: we should skip checking the invisible text, and `jit-spell-correct-word` should skip unfontified misspellings and  open the invisible but fontified ones. I don't know if this is reliable but if it is I think it would be better than skipping invisible text entirely.

**Comment by astoff** [comment]
What you described indeed seems perplexing at first sight, but here's how jit-lock (and jit-spell by extension works). The buffer is fontified lazily as it is displayed, and this includes both regions where you haven't scrolled yet _and_ regions you haven't seen because they're invisible. The catch is that fontification is done in chunks of a reasonable size, so if you have a big invisible chunk, its starting and end portions might get fontified / spellchecked anyway.

Therefore: we have no control about the fontification of hidden regions and that's a good thing. I'm pretty convinced that the right fix is in `jit-spell--search-overlay`. It should be modified to simply skip all invisible text.

**Comment by aikrahguzar** [comment]
> What you described indeed seems perplexing at first sight, but here's how jit-lock (and jit-spell by extension works). The buffer is fontified lazily as it is displayed, and this includes both regions where you haven't scrolled yet _and_ regions you haven't seen because they're invisible. The catch is that fontification is done in chunks of a reasonable size, so if you have a big invisible chunk, its starting and end portions might get fontified / spellchecked anyway.

I understand the lazy part, and you explanation helps with getting a better model of jit-lock. What I don't understand is why invalid misspellings get reported in the invisible region? Since jit-lock passes has passed the region the same region to normal fontification machinery, the characters there must have the faces that cause them not be spellchecked? 

> Therefore: we have no control about the fontification of hidden regions and that's a good thing. I'm pretty convinced that the right fix is in `jit-spell--search-overlay`. It should be modified to simply skip all invisible text.

I will try to change it. Thanks.

**Comment by astoff** [comment]
Can you have a look at https://github.com/astoff/jit-spell/pull/17?

**Comment by aikrahguzar** [comment]
> Can you have a look at #17?

I have tested it and it works as expected. Thanks!
