### ISSUE TITLE
Calling `jit-spell-correct-word` corrects previous word when on the first character of the misspelt word

### ISSUE THREAD

**Issue by meain** [astoff/jit-spell#6]
If I were to call `jit-spell-correct-word` using `M-x`, it seems to be correcting the previous word instead of the one under cursor if I am on the first char. Seems to be fine as long as I am at least one letter in.

**Comment by aikrahguzar** [comment]
This is due to `jit-spell-correct-word` searching backward for a misspelled word which I think is the natural behavior when writing so one can correct a just noticed misspelling a short distance away without moving the point.

This particular problem can be fixed by moving one char forward unless the current one is whitespace. There don't seem to be any negative consequences to that but maybe I am missing some edge case.

**Comment by meain** [comment]
> This particular problem can be fixed by moving one char forward unless the current one is whitespace.

I guess that could work.

**Comment by astoff** [comment]
I'm a bit unsure about this one, since e.g. doing `M-b` at the first character of a word moves you to the previous word (as opposed to when you're one letter in). What should definitely work but doesn't right now is passing 0 as prefix argument.

**Comment by aikrahguzar** [comment]
> I'm a bit unsure about this one, since e.g. doing `M-b` at the first character of a word moves you to the previous word (as opposed to when you're one letter in). What should definitely work but doesn't right now is passing 0 as prefix argument.

What should be behavior of 0 prefix arg if the point is not on a misspelled word?

**Comment by astoff** [comment]
@meain I've not fixed this, with the behavior you suggested (but not released on ELPA yet). Thanks for reporting.
